## 취소와 타임아웃
명시적인 Job에 대해 `cancel` 메서드를 호출해 취소할 수 있다.

~~~kotlin
fun main() = runBlocking {
    doOneTwoThree()
    println("runBlocking: ${Thread.currentThread().name}")
    println("5!")
}

suspend fun doOneTwoThree() = coroutineScope {
    val job1 = launch {
        println("luanch1 : ${Thread.currentThread().name}")
        delay(1000)
        println("3!")
    }
    
    val job2 = launch {
        println("luanch2 : ${Thread.currentThread().name}")
        println("1!")
    }
    
    val job3 = launch {
        println("luanch3 : ${Thread.currentThread().name}")
        delay(500)
        println("2!")
    }
    delay(800)
    
    job1.cancel() // 동작 취소
    job2.cancel()
    job3.cancel()
    println("4!")
}
~~~

실행 결과 : <br>
luanch1 : main @coroutine#2<br>
luanch2 : main @coroutine#3<br>
1!<br>
luanch3 : main @coroutine#4<br>
2!<br>
4!<br>
runBlocking: main @coroutine#1<br>
5!<br>

### 취소 불가능한 Job

~~~kotlin
fun main() = runBlocking {
    doCount()
}

suspend fun doCount() = coroutineScope { 
    val job1 = launch(Dispatchers.Default) { // 그 다음 코드 블록을 다른 스레드에서 수행시킴
        var i = 1
        var nextTime = System.currentTimeMillis() + 100L
        
        while(i <= 10) {
            val currentTime = System.currentTimeMillis()
            if(currentTime >= nextTime) {
                println(i)
                nextTime = currentTime + 100L
                i++
            }
        }
    }
    delay(200)
    job1.cancel()
    //  job1.join()
    println("doCount Done!")
}
~~~

예상했던 실행결과와 조금 다르게 나온다.<br>
실행결과 : 
1<br>
doCount Done!<br>
2<br>
3<br>
4<br>
~~ 생략<br>

실행결과가 이렇게 나오는 이유는 위 코드가 job1을 통해서 cancel하는걸 이해하지 못하게 코딩했기 때문이다.(실제로 cancel 된게 아님!)
job1을 cancel을 한다고 해서 위 작업이 취소가 되는게 아니다.<br>

위 코드에서 두가지 부분이 신경쓰이는데<br>
1. job1이 취소든 종료든 다 끝난 후에 "doCount Done!"을 출력<br>
2. 취소가 되지 않았음<br>

첫 번째로 취소든 종료든 다 끝난 이후에 "doCount Done!"을 출력하려면 주석처리한 job1.join()을 실행시키면 된다.<br>
즉, cancel을 호출한 직후에 취소가 안됐을수도 있기때문에 join을 사용하여 job1의 코루틴의 작업이 끝날 때 까지 기다린다.<br>

### cancelAndJoin
`cancel`을 하고 `join`을 하는 일은 자주 일어나는 일이기 때문에 한번에 하는 `cancelAndJoin`이 있다.

~~~kotlin
job1.cancelAndJoin()
~~~

### cnacel 가능한 코루틴
`isActive`를 호출하면 해당 코루틴이 여전히 활성화된지 확인할 수 있다.

~~~kotlin
suspend fun doCount() = coroutineScope { 
    val job1 = launch(Dispatchers.Default) { // 그 다음 코드 블록을 다른 스레드에서 수행시킴
        var i = 1
        var nextTime = System.currentTimeMillis() + 100L
        
        while(i <= 10 && isActive) { // this.isActive도 가능
            val currentTime = System.currentTimeMillis()
            if(currentTime >= nextTime) {
                println(i)
                nextTime = currentTime + 100L
                i++
            }
        }
    }
    delay(200)
    job1.cancelAndJoin()
    println("doCount Done!")
}
~~~
`isActive`키워드를 사용해서 현재 코루틴이 활성상태인지 확인한다. job1.cancelAndJoin()을 만나면서 코루틴이 취소되고<br>
활성상태가 아니게 되므로 신경쓰였던 2번이 해결된다. cancel가능한 코드를 만드는 핵심은 `isActive`를 사용하는 것이다!<br>
isAcrive를 사용해서 cancel 가능한 코드를 만들 수 있다.<br>


### finally를 같이 사용하기
취소를 가능하게 만들었는데, 취소를 할 때 자원들을 해제 해야하는 경우들이 있다. ex) file, socket 열고 다는것이 짝으로 이루어져 있음.<br>
suspend 함수들은 취소가 되었을 때, JobCancellationException을 발생하기 때문에 try~catch, finally로 대응이 가능하다.

~~~kotlin
suspend fun doOneTwoThree() = coroutineScope { 
    val job1 = launch {
        try {
            // job1이 cancel 된다면 try는 수행되지않고 finally로 넘어감
            println("launch: ${Thread.currentThread().name}")
            delay(1000)
            println("3!")
        } finally {
            println("job1 is finishing!")
            // ex) 파일을 닫아주는 코드
        }
    }
    
    val job2 = launch {
        try {
            println("launch: ${Thread.currentThread().name}")
            delay(1000)
            println("1!")
        } finally {
            println("job2 is finishing!")
            // ex) 소켓을 닫아주는 코드
        }
    }
    delay(800)
    job1.cancel()
    job2.cancel()
}
~~~
실행 결과 : 
launch: main @coroutine#2<br>
launch: main @coroutine#3<br>
job1 is finishing!<br>
job2 is finishing!<br>

취소 가능한 Job에서 자원의 해제를 하기위해서 finally를 사용했다. 하지만 어떤 작업들은 본질적으로 취소를 하면 안되는 작업이 있다.<br>

### 취소 불가능한 블록
어떤 코드는 취소가 불가능해야 한다. 이런 경우에는 `withContext(NonCancellable)`을 이용하면 취소 불가능한 블록을 만들 수 있다.

~~~kotlin
suspend fun doOneTwoThree() = coroutineScope { 
    val job1 = launch {
        withContext(NonCancellable) {
            // 취소가 되지 않고 항상 수행
            println("lauch1: ${Thread.currentThread().name}")
            delay(1000)
            println("3!")
        }
        delay(1000)
        print("job1: end")
    }
    
    val job2 = launch {
        withContext(NonCancellable) {
            println("launch: ${Thread.currentThread().name}")
            delay(1000)
            println("1!")
        }
        delay(1000)
        print("job2: end")
    }
    
    delay(800)
    job1.cancel()
    job2.cancel()
}
~~~

실행 결과 : 
lauch1: main @coroutine#2<br>
launch: main @coroutine#3<br>
3!<br>
1!<br>

withContext(NonCancellable)에 코드블록만 취소가 되지 않고 실행된다.<br>
취소 불가능한 코드를 finally 절에서도 사용할 수 있다. 기본적으로 cancel에 의해서 실행되는데<br>
finally 수행중에 cancel이 일어날 수도 있다. 그런경우에 finally에 취소 불가능한 코드 withContext(NonCancellable)를 넣어 사용할 수 있다.<br>


### 타임 아웃
일정 시간이 끝난 후에 종료하고 싶다면 `withTimeout`을 이용할 수 있다.

~~~koltin
fun main() = runBlociking {
    withTimeout(500) { 
    // 0.5초 이상의 작업이 진행이 되면 강제로 취소하고 예외를 던진다.
    // 취소가 되면 TimeoutCancellationException 예외가 발생.
        doOneTwoThree()
    }
}
~~~

### withTimeoutOfNull
예외를 핸들링하는 것은 귀찮은 일이다. `withTimeoutOfNull`을 이용해 타임 아웃할 때 null을 반환하게 할 수 있다.
~~~kotlin
fun main() = runBlocking {
    val result = withTimeoutOrNull(500) {
        doOneTwoThree()
        true
    } ?: false
    println(result)
}
~~~
`withTimeout`보다 `withTimeoutNull`을 사용하면 조금 더 깔끔하게 코딩할 수 있다.




